export const colorCreation = [
  {
    name: "AÇÚCAR MASCAVO",
    image: "criacao-de-cores/1.png",
    description: "7/35 (20G) + 7/31(10G)",
    brand: "WELLA",
    whiteningBackground: [7],
  },
  {
    name: "AREIA",
    image: "criacao-de-cores/2.png",
    description: "9/7 (10G) + 8/38 (10G) 10/93(10G)",
    brand: "WELLA",
    whiteningBackground: [9, 10],
  },
  {
    name: "AVELÃ",
    image: "criacao-de-cores/3.png",
    description: "7/31 + 8/05 (PARTES IGUAIS)",
    brand: "WELLA",
    whiteningBackground: [7],
  },
  {
    name: "BABY BLOND",
    image: "criacao-de-cores/4.png",
    description: "10/0 (15G) + 0/33 (15G)",
    brand: "WELLA",
    whiteningBackground: [9, 10],
  },
  {
    name: "BAUNILHA",
    image: "criacao-de-cores/5.png",
    description: "10/38 (10G) + 0/0(10G) + 0/33(5G)",
    brand: "WELLA",
    whiteningBackground: [9, 10],
  },
  {
    name: "BEGE CHOCOLATE",
    image: "criacao-de-cores/6.png",
    description: "9/7 + 8/37 + 9/03",
    brand: "WELLA",
    whiteningBackground: [8],
  },
  {
    name: "BEGE DOURADO",
    image: "criacao-de-cores/7.png",
    description: "10/73 + 9/03",
    brand: "WELLA",
    whiteningBackground: [9, 10],
  },
  {
    name: "BRONZE",
    image: "criacao-de-cores/8.png",
    description: "9/43 + 8/05 (PARTES IGUAIS)",
    brand: "WELLA",
    whiteningBackground: [8],
  },
  {
    name: "CANELA",
    image: "criacao-de-cores/9.png",
    description: "7/43(10G)+7/35(20G)",
    brand: "WELLA",
    whiteningBackground: [7],
  },
  {
    name: "CAPUCCINO",
    image: "criacao-de-cores/10.png",
    description: "7/7 + 8/05 + 9/7 (PARTES IGUAIS)",
    brand: "WELLA",
    whiteningBackground: [7],
  },
  {
    name: "CARAMELO BLOND",
    image: "criacao-de-cores/11.png",
    description: "9/43 (15G) + 8/37 (15G)",
    brand: "WELLA",
    whiteningBackground: [8],
  },
  {
    name: "CARAMELO",
    image: "criacao-de-cores/12.png",
    description: "9/43 + 7/35 (PARTES IGUAIS)",
    brand: "WELLA",
    whiteningBackground: [7],
  },
  {
    name: "CHOCOLATE",
    image: "criacao-de-cores/13.png",
    description: "7/7 20G+ 7/43 (5G)",
    brand: "WELLA",
    whiteningBackground: [7],
  },
  {
    name: "DARK CHOCOLATE",
    image: "criacao-de-cores/14.png",
    description: "6/77 + 7/43 (PARTES IGUAIS)",
    brand: "WELLA",
    whiteningBackground: [6, 7],
  },
  {
    name: "ICECREAM",
    image: "criacao-de-cores/15.png",
    description: "10/0 (20G) + 10/36(10G)",
    brand: "WELLA",
    whiteningBackground: [9, 10],
  },
  {
    name: "MANTEIGA",
    image: "criacao-de-cores/16.png",
    description: "10/0 (20G)+ 0/33 (10G)",
    brand: "WELLA",
    whiteningBackground: [9, 10],
  },
  {
    name: "MEL",
    image: "criacao-de-cores/17.png",
    description: "7/43 (10G) + 8/37 (20G) + 0/34 (5G) (PARTES IGUAIS)",
    brand: "WELLA",
    whiteningBackground: [8],
  },
  {
    name: "PÊSSEGO",
    image: "criacao-de-cores/18.png",
    description: "8/05 + 9/43 + 10/0 (PARTES IGUAIS)",
    brand: "WELLA",
    whiteningBackground: [9],
  },
  {
    name: "ROSÊ",
    image: "criacao-de-cores/19.png",
    description: "9/43 (20G) + 10/0(10G)",
    brand: "WELLA",
    whiteningBackground: [9],
  },
  {
    name: "RUIVO",
    image: "criacao-de-cores/20.png",
    description: "9/43 + 7/43 + 8/05 (PARTES IGUAIS)",
    brand: "WELLA",
    whiteningBackground: [8],
  },
  {
    name: "VANILLA",
    image: "criacao-de-cores/21.png",
    description: "10/0 (20G) + 10/69(10G)",
    brand: "WELLA",
    whiteningBackground: [9, 10],
  },
];
